### ISSUE TITLE
taeni segfaulting

### ISSUE THREAD

**Issue by suedi** [simargl/vala-apps#5]
sometimes when I start new taeni instances from within taeni itself I get a segfault.

also sometimes when I start taeni from cmdline in taeni in foreground 
it backgrounds itself

**Comment by simargl** [comment]
What you write is true, Ive tried and also get segmentation fault when starting new taeni windows from another of its window, but i cannot fix it. This Gtk.Application class does some processing in the background, maybe it doesn't allow different windows with same id when using command line. Multiple windows work in every other case...

**Comment by suedi** [comment]
Works now, good job
